# Generated by Django 5.2.8 on 2025-11-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_create_default_categories'),
        ('blog', '0004_post_category'),
    ]

    operations = [
    ]
